// flow-typed signature: 344d3ee28216aa583ef7fe3ac82e998d
// flow-typed version: <<STUB>>/tool-bar-gui_v0.1.2/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tool-bar-gui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tool-bar-gui' {
  declare module.exports: any;
}
